---
settings:
  parallel: true
driver:
  name: docker
  privileged: true

provisioner:
  name: ansible_playbook
  test_repo_uri: https://github.com/hardening-io/tests-mysql-hardening.git
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_verbose: true
  ansible_diff: true
  hosts: all
  roles_path: ../ansible-mysql-hardening/
  playbook: default.yml
  requirements_path: requirements.yml

platforms:
- name: centos-7.1
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum install -y initscripts net-tools wget
- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y
      - mkdir /etc/cron.hourly
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y

suites:
- name: default
