---
driver:
  name: docker
  privileged: true

provisioner:
  name: ansible_playbook
  test_repo_uri: https://github.com/hardening-io/tests-mysql-hardening.git
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_verbose: true
  ansible_diff: true
  hosts: all
  roles_path: ../ansible-mysql-hardening/
  playbook: default.yml
  requirements_path: requirements.yml

platforms:
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04

suites:
- name: default
