---
sudo: false
language: python
python: "2.7"
before_install:
 - apt-get update -qq
 - apt-get install -qq python-apt python-pycurl python-mysqldb
install:
  - pip install ansible
  - echo -e 'localhost ansible_connection=local' > spec/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./spec/inventory' > ansible.cfg
script:
  - ansible-playbook --syntax-check spec/travis.yml
  - ansible-playbook --sudo -v --diff spec/travis.yml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
